
[pt]
    title = "O programador moderno"
    weight = 1
    LanguageName = "pt-br"
    contentDir = "content/pt"
    description = 'Um blog com notícias e informações sobre tecnologia e programação. Além de tutoriais e dicas de Java, Javascript, Python, PHP, GO, Ruby, HTML, CSS, docker, AWS, React, Angular, Vue e outros (não temos preconceito com nenhuma tecnologia), que vão te fazer decolar no mundo do TI!'

[en]
    title = "programming blog"
    weight = 1
    LanguageName = "en"
    contentDir = "content/en"
    description = 'A blog with news and information about technology and programming. In addition to tutorials and tips on Java, Javascript, Python, PHP, GO, Ruby, HTML, CSS, docker, AWS, React, Angular, Vue and others (we have no prejudice against any technology) that will make you take off in the IT world !'

[es]
    title = "blog de programacion"
    weight = 1
    LanguageName = "es"
    contentDir = "content/es"
    description = 'Un blog con noticias e información sobre tecnología y programación. Además de tutoriales y tips sobre Java, Javascript, Python, PHP, GO, Ruby, HTML, CSS, docker, AWS, React, Angular, Vue y otros (no tenemos prejuicios contra ninguna tecnología) que te harán despegar en el mundo de la informatica!'        