    [[main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/en/"

    [[main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/en/post/"

    [[main]]
    name = "Portfolio"
    weight = 300
    identifier = "portfolio"
    url = "/en/portfolio/"

    [[main]]
    name = "About"
    weight = 400
    identifier = "about"
    url = "/en/about/"

    # [[menu.main]]
    # name = "Accomplishments"
    # weight = 500
    # identifier = "accomplishments"

    # [[menu.main]]
    # name = "Awards"
    # weight = 510
    # identifier = "awards"
    # url = "/awards/"
    # parent = "accomplishments"  

    # [[menu.main]]
    # name = "Certifications"
    # weight = 520
    # identifier = "certifications"
    # url = "/certifications/"
    # parent = "accomplishments"

    [[main]]
    name = "Contato"
    weight = 600
    identifier = "contact"
    url = "/en/contact/"

    [[footer]]
    name = "Renan-Dev"
    weight = 1
    identifier = "imprint"
    url = "/en/imprint/"