profilePicture = "images/imagem.jpeg"
gtagId="G-RG5L7KE8CQ"
favicon = "favicons/"
commentoURL="https://commento.updevblog.com/js/commento.js"
contactFormAction="https://kwesforms.com/api/foreign/forms/TWboUdDBnvqStejn56BU"
[umami]
serverURL="https://umami.updevblog.com"
id="48a61b1e-2fe0-4f38-8d5d-d01af53a7254"
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/renan-ribeiro-b1368872/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/kusmin"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/renanlagee/"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:renan.lagee@gmail.com"

