
[pt]
title = "Meu blog"
weight = 1
LanguageName = "EN"
contentDir = "content/english"
description = 'Meu blog descrição'

[ar]
title = "فلانة الفلانية"
description = "أنا أعمل كمطورة ويب في شركة س"
contentDir = "content/arabic" 
weight = 2
LanguageDirection = "rtl" 
LanguageName = "AR"
