---
label: default
hide_body: false
fields:
- type: text
  name: author
  label: author
- type: text
  name: title
  label: title
- type: text
  name: redirectUrl
  label: redirectUrl
- type: datetime
  name: date
  label: date
- type: list
  name: tags
  label: tags
- type: list
  name: series
  label: series
- type: boolean
  name: math
  label: math
- type: list
  name: categories
  label: categories
- type: list
  name: aliases
  label: aliases
- type: file
  name: thumbnail
  label: thumbnail
pages:
- content/pt/portfolio/criacao-de-sites-estaticos.md
- 'content/pt/post/Podman: Entendendo o Podman: Funcionamento, Aplicações e Prós e
  Contras.md'
- content/pt/post/construindo-uma-api-de-chat-em-tempo-real-com-nestjs-websocket-e-prisma.md
- content/pt/post/criando-uma-api-conceitos.md
- content/pt/post/desenvolvimento-local-localstack.md
- content/pt/post/docker-dockerizando-o-nodejs.md
- content/pt/post/gerenciadores-de-versao-nvm.md
- content/pt/post/gerenciadores-de-versao-rvm.md
- content/pt/post/gerenciadores-de-versao-sdkman.md
- content/pt/post/linux-gerenciamento-de-processos-parte-2.md
- content/pt/post/linux-gerenciamento-de-processos.md
- content/pt/post/linux-gerenciamento-de-usuarios-e.md
- content/pt/post/linux-permissoes-de-arquivos-e-diretorios.md
- content/pt/post/nestjs-adicionando-autenticacao-e-autorizacao-com-jwt-e-passport.js.md
- content/pt/post/nestjs-com-prisma-implementando-testes-de-unidade-e-integracao.md
- content/pt/post/nestjs-e-graphql-criando-apis-flexiveis-e-eficazes.md
- content/pt/post/principios-da-programacao-linguagem-de-programacao.md
- content/pt/post/principios-da-programacao-o-que-e-programacao.md
- content/pt/post/sites-dinamicos-x-sites-estaticos.md
