---
label: default
hide_body: false
fields:
- type: text
  name: author
  label: author
- type: text
  name: title
  label: title
- type: text
  name: redirectUrl
  label: redirectUrl
- type: datetime
  name: date
  label: date
- type: list
  name: tags
  label: tags
- type: list
  name: series
  label: series
- type: boolean
  name: math
  label: math
- type: list
  name: categories
  label: categories
- type: list
  name: aliases
  label: aliases
- type: file
  name: thumbnail
  label: thumbnail
pages:
- content/pt/post/gerenciadores-de-versao-rvm.md
- content/pt/post/gerenciadores-de-versao-sdkman.md
- content/pt/post/sites-dinamicos-x-sites-estaticos.md
