name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install    

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.101.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/ajuste
        run: hugo --minify

      - name: Build Tina CMS
        run: npm run build  

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HUGODEPLOY }}
          external_repository: kusmin/blog_dev
          publish_dir: ./public
          #   keep_files: true
          user_name: renan
          user_email: renan.lagee@gmail.com
          publish_branch: master
          cname: updevblog.com